C_FILE="hellopeter.c serial_port.c  alsa_play.c alsa_record.c gpio.c fifo.c log.c volume_control.c"
LIB_FILE="-lasound -lpthread"
#O_FILE="hellopeter.o serial_port.o  alsa_play.o alsa_record.o gpio.o fifo.o log.o "
#gcc -o $O_FILE $LIB_FILE -o hellopeter
gcc $C_FILE $LIB_FILE -o hellopeter





